### PR TITLE
Update context.py

### PR DESCRIPTION
**Pull request by tkkhhaarree**

### CODE REVIEW

**Comment by yashbeer** [comment]
Have you checked whether removing TRAFFIC variable from context will affect the templates?

**Comment by tkkhhaarree** [comment]
I also removed the div with id traffic from starbase.html template.

Also i was having problem in running the site in localhost so i couldn't
test it. I installed all the required modules from requirements folder.
Then i used the run command as written in readme but server wont open. I
also tried python manage.py runserver command but still it wont run. Can
you tell me how to run the site?

**Comment by yashbeer** [comment]
Which version of python are you using?

**Comment by tkkhhaarree** [comment]
Python 3.5.2

**Comment by yashbeer** [comment]
what is the error you are getting?

**Comment by tkkhhaarree** [comment]
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must
not be empty.

**Comment by tkkhhaarree** [comment]
I can't see any settings.py file in project. usually the SECRET_KEY resides
in settings.py. instead there is a whole settings folder

**Comment by yashbeer** [comment]
We have custom settings written in /biostar/settings/base.py

I will help you offline and resolve the installation.

**Pull request closed without merging**
